---
title: "speciesdiv_park"
output: html_document
date: "2023-02-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyr)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(plotly)
library(readr)
library(RColorBrewer)
library(patchwork)
library(knitr)
library(DT)
library(gt)
library(base)

#creating code for dashboard that is compatible with different spatial scales
```

```{r}
species_rich <- read_csv(here::here("DataIn", "SpeciesDiversity_LongFormat.csv"))
species_rich <- species_rich %>%
  tidyr::replace_na(list(Nativity = "Unknown"))

#Summarizing nativity of species per plot
#Using Species_Diversity_ID not Plant Code because doesn't account for sp level differences 
 
plot_nativity <- species_rich %>%
  dplyr::filter(Sample_Depth_Code != 0) %>%
  dplyr::mutate(Sample_Depth_Code = as.factor(Sample_Depth_Code)
         ) %>%
  dplyr::group_by(Plot_Code, Species_Diversity_ID,
           Nativity) %>%
  dplyr::count(Nativity)

plot_nativity <- plot_nativity %>%
  dplyr::group_by(Plot_Code) %>%
  dplyr::count(Nativity)

plot_nativity <- plot_nativity %>%
  tidyr::pivot_wider(
    names_from = Nativity, 
    values_from = n
  )

plot_nativity <- plot_nativity %>%
  dplyr::rename_at(vars(-Plot_Code),function(x) paste0(x,"<sup>a</sup>"))

###400 m2 
plot_total <- species_rich %>%
  dplyr::filter(Sample_Depth_Code != 0) %>%
  dplyr::mutate(Sample_Depth_Code = as.factor(Sample_Depth_Code), 
                Growth_Form = toupper(Growth_Form)) %>%
  dplyr::group_by(Plot_Code, Species_Diversity_ID, Growth_Form)%>%
  dplyr::count(Growth_Form)

plot_total <- plot_total %>%
  dplyr::group_by(Plot_Code, Growth_Form) %>%
  dplyr::summarize(Count = n())

###100m2
plot_mod100 <- species_rich %>%
  dplyr::filter(Sample_Depth_Code != 0) %>%
  dplyr::mutate(Sample_Depth_Code = as.factor(Sample_Depth_Code), 
         Growth_Form = toupper(Growth_Form)) %>%
  dplyr::group_by(
                  Plot_Code, 
           Growth_Form,
           Module, 
           Species_Diversity_ID) %>%
  dplyr::count(Species_Diversity_ID)%>%
  ungroup() %>%
  dplyr::group_by(
                  Plot_Code, 
                  Growth_Form,
                  Module, 
                  Species_Diversity_ID) %>%
  dplyr::count(Module) %>%
  ungroup()%>%
  dplyr::group_by(
                  Plot_Code, 
                  Growth_Form,
                  Module) %>%
  dplyr::summarize(numSpecies = sum(n))%>%
  ungroup() %>%
  dplyr::group_by( 
                  Plot_Code,
                  Growth_Form) %>%
  dplyr::summarize(Mod100 = mean(numSpecies)) %>%
  ungroup() %>%
  group_by(Plot_Code,
           Growth_Form) %>%
  dplyr::summarize(Mod100 = sum(Mod100))%>%
  dplyr::ungroup()

### 10m2
plot_mod10 <- species_rich %>%
  dplyr::filter(Sample_Depth_Code != 0, 
         Sample_Depth_Code != 1) %>%
  dplyr::mutate(Sample_Depth_Code = as.factor(Sample_Depth_Code), 
         Growth_Form = toupper(Growth_Form)) %>%
  dplyr::group_by(
                  Plot_Code, 
           Growth_Form,
           Module,
           Corner,
           Species_Diversity_ID) %>%
  dplyr::count(Species_Diversity_ID)%>%
  ungroup() %>%
  dplyr::group_by(
                  Plot_Code, 
           Growth_Form,
           Module,
           Corner,
           Species_Diversity_ID) %>%
  dplyr::count(Corner) %>%
  ungroup()%>%
  dplyr::group_by(
                  Plot_Code, 
           Growth_Form,
           Module,
           Corner) %>%
  dplyr::summarize(numSpecies = sum(n)) %>%
  ungroup() %>%
  dplyr::group_by(
                  Plot_Code,
                  Growth_Form) %>%
  dplyr::summarize(Mod10 = mean(numSpecies)) %>%
  ungroup() %>%
  dplyr::group_by(Plot_Code, 
           Growth_Form) %>%
  dplyr::summarize(Mod10 = sum(Mod10))

###1m2
plot_mod1 <- species_rich %>%
  dplyr::filter(Sample_Depth_Code == 3) %>%
  dplyr::mutate(Sample_Depth_Code = as.factor(Sample_Depth_Code), 
         Growth_Form = toupper(Growth_Form)) %>%
  dplyr::group_by(
                  Plot_Code, 
           Growth_Form, 
           Module,
           Corner,
           Species_Diversity_ID) %>%
  dplyr::count(Species_Diversity_ID)%>%
  ungroup()%>%
  dplyr::group_by(
                  Plot_Code, 
           Growth_Form, 
           Module, 
           Corner,
           Species_Diversity_ID) %>%
  dplyr::count(Corner)%>%
  ungroup()%>%
  dplyr::group_by(
                  Plot_Code,
           Growth_Form,
           Module, 
           Corner) %>%
  dplyr::summarize(numSpecies = sum(n))%>%
  ungroup()%>%
  dplyr::group_by(
                  Plot_Code,
                  Growth_Form) %>%
  dplyr::summarize(Mod1 = mean(numSpecies))%>%
  ungroup()%>%
  group_by(Plot_Code,
           Growth_Form) %>%
  summarize(Mod1 = sum(Mod1))
```

```{r}
### full join
plot_rich <- Reduce(function (...) { merge(..., all = TRUE) },  
                           list(plot_total, plot_mod100, plot_mod10, plot_mod1))
```

```{r}
makeInitials <- function(charVec) {
  make.unique(vapply(strsplit(toupper(charVec), " "), 
                     function(x) paste(substr(x, 1, 1), collapse = ""), 
                     vector("character", 1L)))
}

plot_rich <- plot_rich %>%
    mutate(Growth_Form = mapply(function(charVec) makeInitials(charVec), Growth_Form)) #BHT = `GROUP`

plot_rich <- plot_rich %>%
  tidyr::pivot_wider(
    names_from = Growth_Form, 
    values_from = c(Count,
                    Mod100,
                    Mod10, 
                    Mod1), 
    names_prefix = "")

plot_rich <- Reduce(function (...) { merge(..., all = TRUE) },  # Full join
                           list(plot_nativity, plot_rich))

plot_rich <- round_df(plot_rich, 1)

plot_rich <- plot_rich %>%
    replace(is.na(.), 0)

plot_rich <- plot_rich %>%
  dplyr::rename_at(vars(starts_with("Count_")), 
            list(~paste(.,"<sup>a</sup>"))) %>%
  dplyr::rename_at(vars(starts_with("Mod100_")), 
            list(~paste(.,"<sup>b</sup>"))) %>%
  dplyr::rename_at(vars(starts_with("Mod10_")), 
            list(~paste(., "<sup>c</sup>"))) %>%
  dplyr::rename_at(vars(starts_with("Mod1_")), 
            list(~paste(., "<sup>d</sup>")))

names(plot_rich) = gsub(pattern = "Count_", replacement = "", x = names(plot_rich))
names(plot_rich) = gsub(pattern = "Mod100_", replacement = "", x = names(plot_rich))
names(plot_rich) = gsub(pattern = "Mod10_", replacement = "", x = names(plot_rich))
names(plot_rich) = gsub(pattern = "Mod1_", replacement = "", x = names(plot_rich))

df_plotrich <- plot_rich
```

###PARK

```{r}

park_nativity <- species_rich %>%
  dplyr::filter(Sample_Depth_Code != 0) %>%
  dplyr::mutate(Sample_Depth_Code = as.factor(Sample_Depth_Code)
         ) %>%
  dplyr::group_by(Park_Code, Plot_Code, Species_Diversity_ID,
           Nativity) %>%
  dplyr::count(Nativity)

park_nativity <- park_nativity %>%
  dplyr::group_by(Park_Code) %>%
  dplyr::count(Nativity)

park_nativity <- park_nativity %>%
  tidyr::pivot_wider(
    names_from = Nativity, 
    values_from = n
  )

park_nativity <- park_nativity %>%
  dplyr::rename_at(vars(-Park_Code),function(x) paste0(x,"<sup>a</sup>"))

###400 m2 
park_total <- species_rich %>%
  dplyr::filter(Sample_Depth_Code != 0) %>%
  dplyr::mutate(Sample_Depth_Code = as.factor(Sample_Depth_Code), 
                Growth_Form = toupper(Growth_Form)) %>%
  dplyr::group_by(Park_Code, Plot_Code, Species_Diversity_ID, Growth_Form)%>%
  dplyr::count(Growth_Form)

park_total <- park_total %>%
  dplyr::group_by(Park_Code, Growth_Form) %>%
  dplyr::summarize(Count = n())

###100m2
park_mod100 <- species_rich %>%
  dplyr::filter(Sample_Depth_Code != 0) %>%
  dplyr::mutate(Sample_Depth_Code = as.factor(Sample_Depth_Code), 
         Growth_Form = toupper(Growth_Form)) %>%
  dplyr::group_by(Park_Code,
                  Plot_Code, 
           Growth_Form,
           Module, 
           Species_Diversity_ID) %>%
  dplyr::count(Species_Diversity_ID)%>%
  ungroup() %>%
  dplyr::group_by(Park_Code,
                  Plot_Code, 
                  Growth_Form,
                  Module, 
                  Species_Diversity_ID) %>%
  dplyr::count(Module) %>%
  ungroup()%>%
  dplyr::group_by(Park_Code,
                  Plot_Code, 
                  Growth_Form,
                  Module) %>%
  dplyr::summarize(numSpecies = sum(n))%>%
  ungroup() %>%
  dplyr::group_by(Park_Code, 
                  Plot_Code,
                  Growth_Form) %>%
  dplyr::summarize(Mod100 = mean(numSpecies)) %>%
  ungroup() %>%
  group_by(Park_Code,
           Growth_Form) %>%
  dplyr::summarize(Mod100 = sum(Mod100))%>%
  dplyr::ungroup()

### 10m2
park_mod10 <- species_rich %>%
  dplyr::filter(Sample_Depth_Code != 0, 
         Sample_Depth_Code != 1) %>%
  dplyr::mutate(Sample_Depth_Code = as.factor(Sample_Depth_Code), 
         Growth_Form = toupper(Growth_Form)) %>%
  dplyr::group_by(Park_Code,
                  Plot_Code, 
           Growth_Form,
           Module,
           Corner,
           Species_Diversity_ID) %>%
  dplyr::count(Species_Diversity_ID)%>%
  ungroup() %>%
  dplyr::group_by(Park_Code,
                  Plot_Code, 
           Growth_Form,
           Module,
           Corner,
           Species_Diversity_ID) %>%
  dplyr::count(Corner) %>%
  ungroup()%>%
  dplyr::group_by(Park_Code,
                  Plot_Code, 
           Growth_Form,
           Module,
           Corner) %>%
  dplyr::summarize(numSpecies = sum(n)) %>%
  ungroup() %>%
  dplyr::group_by(Park_Code,
                  Plot_Code,
                  Growth_Form) %>%
  dplyr::summarize(Mod10 = mean(numSpecies)) %>%
  ungroup() %>%
  dplyr::group_by(Park_Code, 
           Growth_Form) %>%
  dplyr::summarize(Mod10 = sum(Mod10))

###1m2
park_mod1 <- species_rich %>%
  dplyr::filter(Sample_Depth_Code == 3) %>%
  dplyr::mutate(Sample_Depth_Code = as.factor(Sample_Depth_Code), 
         Growth_Form = toupper(Growth_Form)) %>%
  dplyr::group_by(Park_Code,
                  Plot_Code, 
           Growth_Form, 
           Module,
           Corner,
           Species_Diversity_ID) %>%
  dplyr::count(Species_Diversity_ID)%>%
  ungroup()%>%
  dplyr::group_by(Park_Code,
                  Plot_Code, 
           Growth_Form, 
           Module, 
           Corner,
           Species_Diversity_ID) %>%
  dplyr::count(Corner)%>%
  ungroup()%>%
  dplyr::group_by(Park_Code,
                  Plot_Code,
           Growth_Form,
           Module, 
           Corner) %>%
  dplyr::summarize(numSpecies = sum(n))%>%
  ungroup()%>%
  dplyr::group_by(Park_Code,
                  Plot_Code,
                  Growth_Form) %>%
  dplyr::summarize(Mod1 = mean(numSpecies))%>%
  ungroup()%>%
  group_by(Park_Code,
           Growth_Form) %>%
  summarize(Mod1 = sum(Mod1))
```

```{r}
### full join
park_rich <- Reduce(function (...) { merge(..., all = TRUE) },  
                           list(park_total, park_mod100, park_mod10, park_mod1))
```

```{r}
makeInitials <- function(charVec) {
  make.unique(vapply(strsplit(toupper(charVec), " "), 
                     function(x) paste(substr(x, 1, 1), collapse = ""), 
                     vector("character", 1L)))
}

park_rich <- park_rich %>%
    mutate(Growth_Form = mapply(function(charVec) makeInitials(charVec), Growth_Form)) #BHT = `GROUP`

park_rich <- park_rich %>%
  tidyr::pivot_wider(
    names_from = Growth_Form, 
    values_from = c(Count,
                    Mod100,
                    Mod10, 
                    Mod1), 
    names_prefix = "")

park_rich <- Reduce(function (...) { merge(..., all = TRUE) },  # Full join
                           list(park_nativity, park_rich))

park_rich <- round_df(park_rich, 1)

park_rich <- park_rich %>%
    replace(is.na(.), 0)

park_rich <- park_rich %>%
  dplyr::rename_at(vars(starts_with("Count_")), 
            list(~paste(.,"<sup>a</sup>"))) %>%
  dplyr::rename_at(vars(starts_with("Mod100_")), 
            list(~paste(.,"<sup>b</sup>"))) %>%
  dplyr::rename_at(vars(starts_with("Mod10_")), 
            list(~paste(., "<sup>c</sup>"))) %>%
  dplyr::rename_at(vars(starts_with("Mod1_")), 
            list(~paste(., "<sup>d</sup>")))

names(park_rich) = gsub(pattern = "Count_", replacement = "", x = names(park_rich))
names(park_rich) = gsub(pattern = "Mod100_", replacement = "", x = names(park_rich))
names(park_rich) = gsub(pattern = "Mod10_", replacement = "", x = names(park_rich))
names(park_rich) = gsub(pattern = "Mod1_", replacement = "", x = names(park_rich))

df_parkrich <- park_rich
```


###Subunit


```{r}
subunit_nativity <- species_rich %>%
  dplyr::filter(Sample_Depth_Code != 0) %>%
  dplyr::mutate(Sample_Depth_Code = as.factor(Sample_Depth_Code)
         ) %>%
  dplyr::group_by(Subunit_Code, Plot_Code, Species_Diversity_ID,
           Nativity) %>%
  dplyr::count(Nativity)

subunit_nativity <- subunit_nativity %>%
  dplyr::group_by(Subunit_Code) %>%
  dplyr::count(Nativity)

subunit_nativity <- subunit_nativity %>%
  tidyr::pivot_wider(
    names_from = Nativity, 
    values_from = n
  )

subunit_nativity <- subunit_nativity %>%
  dplyr::rename_at(vars(-Subunit_Code),function(x) paste0(x,"<sup>a</sup>"))

###400 m2 
subunit_total <- species_rich %>%
  dplyr::filter(Sample_Depth_Code != 0) %>%
  dplyr::mutate(Sample_Depth_Code = as.factor(Sample_Depth_Code), 
                Growth_Form = toupper(Growth_Form)) %>%
  dplyr::group_by(Subunit_Code, Plot_Code, Species_Diversity_ID, Growth_Form)%>%
  dplyr::count(Growth_Form)

subunit_total <- subunit_total %>%
  dplyr::group_by(Subunit_Code, Growth_Form) %>%
  dplyr::summarize(Count = n())

###100m2
subunit_mod100 <- species_rich %>%
  dplyr::filter(Sample_Depth_Code != 0) %>%
  dplyr::mutate(Sample_Depth_Code = as.factor(Sample_Depth_Code), 
         Growth_Form = toupper(Growth_Form)) %>%
  dplyr::group_by(Subunit_Code,
                  Plot_Code, 
           Growth_Form,
           Module, 
           Species_Diversity_ID) %>%
  dplyr::count(Species_Diversity_ID)%>%
  ungroup() %>%
  dplyr::group_by(Subunit_Code,
                  Plot_Code, 
                  Growth_Form,
                  Module, 
                  Species_Diversity_ID) %>%
  dplyr::count(Module) %>%
  ungroup()%>%
  dplyr::group_by(Subunit_Code,
                  Plot_Code, 
                  Growth_Form,
                  Module) %>%
  dplyr::summarize(numSpecies = sum(n))%>%
  ungroup() %>%
  dplyr::group_by(Subunit_Code, 
                  Plot_Code,
                  Growth_Form) %>%
  dplyr::summarize(Mod100 = mean(numSpecies)) %>%
  ungroup() %>%
  group_by(Subunit_Code,
           Growth_Form) %>%
  dplyr::summarize(Mod100 = sum(Mod100))%>%
  dplyr::ungroup()

### 10m2
subunit_mod10 <- species_rich %>%
  dplyr::filter(Sample_Depth_Code != 0, 
         Sample_Depth_Code != 1) %>%
  dplyr::mutate(Sample_Depth_Code = as.factor(Sample_Depth_Code), 
         Growth_Form = toupper(Growth_Form)) %>%
  dplyr::group_by(Subunit_Code,
                  Plot_Code, 
           Growth_Form,
           Module,
           Corner,
           Species_Diversity_ID) %>%
  dplyr::count(Species_Diversity_ID)%>%
  ungroup() %>%
  dplyr::group_by(Subunit_Code,
                  Plot_Code, 
           Growth_Form,
           Module,
           Corner,
           Species_Diversity_ID) %>%
  dplyr::count(Corner) %>%
  ungroup()%>%
  dplyr::group_by(Subunit_Code,
                  Plot_Code, 
           Growth_Form,
           Module,
           Corner) %>%
  dplyr::summarize(numSpecies = sum(n)) %>%
  ungroup() %>%
  dplyr::group_by(Subunit_Code,
                  Plot_Code,
                  Growth_Form) %>%
  dplyr::summarize(Mod10 = mean(numSpecies)) %>%
  ungroup() %>%
  dplyr::group_by(Subunit_Code, 
           Growth_Form) %>%
  dplyr::summarize(Mod10 = sum(Mod10))

###1m2
subunit_mod1 <- species_rich %>%
  dplyr::filter(Sample_Depth_Code == 3) %>%
  dplyr::mutate(Sample_Depth_Code = as.factor(Sample_Depth_Code), 
         Growth_Form = toupper(Growth_Form)) %>%
  dplyr::group_by(Subunit_Code,
                  Plot_Code, 
           Growth_Form, 
           Module,
           Corner,
           Species_Diversity_ID) %>%
  dplyr::count(Species_Diversity_ID)%>%
  ungroup()%>%
  dplyr::group_by(Subunit_Code,
                  Plot_Code, 
           Growth_Form, 
           Module, 
           Corner,
           Species_Diversity_ID) %>%
  dplyr::count(Corner)%>%
  ungroup()%>%
  dplyr::group_by(Subunit_Code,
                  Plot_Code,
           Growth_Form,
           Module, 
           Corner) %>%
  dplyr::summarize(numSpecies = sum(n))%>%
  ungroup()%>%
  dplyr::group_by(Subunit_Code,
                  Plot_Code,
                  Growth_Form) %>%
  dplyr::summarize(Mod1 = mean(numSpecies))%>%
  ungroup()%>%
  group_by(Subunit_Code,
           Growth_Form) %>%
  summarize(Mod1 = sum(Mod1))
```

```{r}
### full join
subunit_rich <- Reduce(function (...) { merge(..., all = TRUE) },  
                           list(subunit_total, subunit_mod100, subunit_mod10, subunit_mod1))
```

```{r}
makeInitials <- function(charVec) {
  make.unique(vapply(strsplit(toupper(charVec), " "), 
                     function(x) paste(substr(x, 1, 1), collapse = ""), 
                     vector("character", 1L)))
}

subunit_rich <- subunit_rich %>%
    mutate(Growth_Form = mapply(function(charVec) makeInitials(charVec), Growth_Form)) #BHT = `GROUP`

subunit_rich <- subunit_rich %>%
  tidyr::pivot_wider(
    names_from = Growth_Form, 
    values_from = c(Count,
                    Mod100,
                    Mod10, 
                    Mod1), 
    names_prefix = "")

subunit_rich <- Reduce(function (...) { merge(..., all = TRUE) },  # Full join
                           list(subunit_nativity, subunit_rich))

subunit_rich <- round_df(subunit_rich, 1)

subunit_rich <- subunit_rich %>%
    replace(is.na(.), 0)

subunit_rich <- subunit_rich %>%
  dplyr::rename_at(vars(starts_with("Count_")), 
            list(~paste(.,"<sup>a</sup>"))) %>%
  dplyr::rename_at(vars(starts_with("Mod100_")), 
            list(~paste(.,"<sup>b</sup>"))) %>%
  dplyr::rename_at(vars(starts_with("Mod10_")), 
            list(~paste(., "<sup>c</sup>"))) %>%
  dplyr::rename_at(vars(starts_with("Mod1_")), 
            list(~paste(., "<sup>d</sup>")))

names(subunit_rich) = gsub(pattern = "Count_", replacement = "", x = names(subunit_rich))
names(subunit_rich) = gsub(pattern = "Mod100_", replacement = "", x = names(subunit_rich))
names(subunit_rich) = gsub(pattern = "Mod10_", replacement = "", x = names(subunit_rich))
names(subunit_rich) = gsub(pattern = "Mod1_", replacement = "", x = names(subunit_rich))

df_subunitrich <- subunit_rich
```
