#R CODE CHUNKS
#include = FALSE prevents code and results from appearing in the finished file. R Markdown still runs the code in the chunk, and the results can be used by other chunks.
#echo = FALSE prevents code, but not the results from appearing in the finished file. This is a useful way to embed figures.
#message = FALSE prevents messages that are generated by code from appearing in the finished file.
#warning = FALSE prevents warnings that are generated by code from appearing in the finished.
#fig.cap = "..." adds a caption to graphical results.



#Janitor package for converting outside csv column names to snake case
#UNTESTED FUNCTION TO CONNECT TO SQL SERVER DATABASE TO flexdashboard::
connection = 
  dbConnect(drv = MySQL(), 
            user = "xxx", 
            password = 'xxx', 
            host = 'mybookdatabase.cgac79lt7rx0.us-east-2.rds.amazonaws.com', 
            port = 3306, 
            dbname = 'nikita99')
#combining multiple shapefiles

library(sf)
#list all the shapefiles within the folder location

file_list <- list.files("shapefile/folder/location", pattern = "*shp", full.names = TRUE)
#read all shapefiles, store as a list

shapefile_list <- lapply(file_list, read_sf)
#append the separate shapefiles, in my example there are 4 shapefiles, this can probably be improved by using a for loop or apply function for a longer list.

all_schools <- rbind(shapefile_list[[1]], shapefile_list[[2]], shapefile_list[[3]])

#gets ride of scientific notation in the global options 
options(scipen=999)

#rounding function 
 round_df <- function(x, digits) {
   # round all numeric variables
   # x: data frame 
   # digits: number of digits to round
   numeric_columns <- sapply(x, mode) == 'numeric'
   x[numeric_columns] <-  round(x[numeric_columns], digits)
   x
 }
#IF dev tools is struggling to download   
 if (!require("devtools")) install.packages("devtools")
 devtools::install_github("rstudio/httpuv")
 library(devtools)

#Streamlined version of prop table -> DF
as.data.frame(prop.table(table(data_frame$column)))

#use locale = locale(encoding="latin1") when struggling to import dataset with weird font or formatting
Plot_Metrics <- read_csv("SFCN_Plot_Metrics.csv", locale=locale(encoding="latin1"))

#Split by index position using separate
Plot_Locations_Conversion <- Plot_Locations_Conversion %>%
  separate(UTM_Zone, c("Zone", "NA"), 2)

#useful website on how to create a CRS and sf/st/rgdal packages https://inbo.github.io/tutorials/tutorials/spatial_crs_coding/
#:~:text=How%20to%20specify%20a%20CRS%20in%20R%3F%201,that%20might%20still%20work%2C%20their%20usage%20is%20discouraged%29.

#EXAMPLE OF CONVERTING TO LATITUDE AND LONGITUDE FROM utm NAD83 COORDINATES

# n + 100 are converting UTM to Lat and Long as a check #MOVE OR KILL YOUR DARLINGS

Plot_Locations_Conversion <- Plot_Locations %>%
  dplyr::select(Plot_Code, UTMX, UTMY, UTM_Zone)

Plot_Locations_Conversion <- drop_na(Plot_Locations_Conversion)

unique(Plot_Locations_Conversion$UTM_Zone)

Plot_Locations_Conversion <- Plot_Locations_Conversion %>%
  separate(UTM_Zone, c("Zone", "NA"), 2)

Plot_Locations_Conversion

# Splitting Zones
Zone_split = split(Plot_Locations_Conversion, Plot_Locations_Conversion$Zone)



#ZONE 17 Conversion Check
Zone_17_OG <- as.data.frame(Zone_split$`17`)

#select utm coordinates
Zone_17 <- Zone_17_OG %>%
  dplyr::select(UTMX, UTMY)

coordinates(Zone_17) <- ~UTMX + UTMY

#creates this projection for NAD83 and Zone 17
proj4string(Zone_17) <- CRS("+init=epsg:26917")

#coding what projection we want it in lat/lon EPSG:4326
Zone_17_latlong <- spTransform(Zone_17, CRS("+init=epsg:4326"))

#creating a dataframe from the coordinates
Zone_17_latlong <- as.data.frame(coordinates(Zone_17_latlong))

#renaming to Lat and Long
Zone_17_latlong <- Zone_17_latlong %>%
  dplyr::rename(Longitude = UTMX, 
                Latitude = UTMY)
#Recombining UTM coords with lat/long coords - assuming that order hasn't changed
Zone_17_Plots <- cbind(Zone_17_OG, Zone_17_latlong)

#subsetting dataframe to needed columns
Zone_17_Plots <- Zone_17_Plots %>%
  dplyr::select(Plot_Code, UTMX, UTMY, Longitude, Latitude, Zone)


#Zone 20 Conversion CHECK 
Zone_20_OG <- as.data.frame(Zone_split$`20`)

Zone_20 <- Zone_20_OG %>%
  dplyr::select(UTMX, UTMY)


coordinates(Zone_20) <- ~UTMX + UTMY

proj4string(Zone_20) <- CRS("+init=epsg:26920")

Zone_20_latlong <- spTransform(Zone_20, CRS("+init=epsg:4326"))

Zone_20_latlong <- as.data.frame(coordinates(Zone_20_latlong))

Zone_20_latlong <- Zone_20_latlong %>%
  dplyr::rename(Longitude = UTMX, 
                Latitude = UTMY)

Zone_20_Plots <- cbind(Zone_20_OG, Zone_20_latlong)

Zone_20_Plots <- Zone_20_Plots %>%
  dplyr::select(Plot_Code, UTMX, UTMY, Longitude, Latitude, Zone)

Zone_20_Plots


#Checking if converted Latitude and Longitude values match from database

latlongcheck <- rbind(Zone_17_Plots, Zone_20_Plots)

latlongcheck <- full_join(latlongcheck, Plot_Locations, by = c("Plot_Code", "UTMX", "UTMY"))

latlongcheck %>%
  dplyr::select(Plot_Code, Latitude.x, Latitude.y, Longitude.x, Longitude.y)

#Adding a crs to latitude and longitude is both redundant and not compatible with leaflet and the sf()
#useful to writing a crs to a set of coordinates 
BISCMAN_Plot_Locations

crs_wgs84 <- st_crs(4326)
BISCMAN_Plot_Locations <- st_as_sf(BISCMAN_Plot_Locations, coords = c("Latitude", "Longitude"))
st_crs(BISCMAN_Plot_Locations) <- 4326
BISCMAN_Plot_Locations

#changing crs for a shapefile in this example to wgs84 latlong
data = data.shp
data <- st_transform(data, crs = 4326)


#RENAMING COLUMNS


Orange_df = Orange %>% rename_at(vars(starts_with("T")), 
                                 funs(str_replace(., "Tree", "Tree_Type")))
Orange_df = Orange %>% rename_if(is.numeric, funs(str_replace(., "age", "tree_life")))
Orange_df

names(GULN) = gsub(pattern = "_SMW", replacement = "", x = names(GULN))

names(species_rich_test) <- c("Plot Code", "Native<sup>a</sup>")

#selecting values based on string 
CUPN_FODO <- tree_basics_df %>%
     filter(grepl("DONE", Plot_Code)| 
               grepl("HEIM", Plot_Code))


#finding duplicate columns with different community_1 names


wtf <- USNVC_parent %>%
  dplyr::mutate(Community_1 = as.factor(Community_1)) %>%
  dplyr::group_by(Plot_Code, Community_1) %>%
  dplyr::summarize(obs = n()) 

wtflist <- wtf %>%
  dplyr::filter(duplicated(Plot_Code))

wtf <- wtf %>%
  dplyr::filter(Plot_Code %in% wtflist$Plot_Code)


#when assigning a character/string to another value, how to access it in a dataset
sss <- "Park_Code"


tree_full %>%
  dplyr::filter(!!as.name(sss) == "STRI")


 select(all_of(sss))


